[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = [
    "src/api-functions/backend-openapi-v1.yaml",
    "src/api-functions/swagger-ui.css",
    "src/api-functions/swagger-ui-bundle.js",
    "src/api-functions/swagger-ui-standalone-preset.js",
    "src/api-functions/favicon-16x16.png",
    "src/api-functions/favicon-32x32.png"
  ]
  directory = "src/api-functions/"

[[redirects]]
  force = true
  from = "/v1/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  force = true
  from = "/src/*"
  status = 500
  to = "/"

[build]
  command = "npm run copy-functions-resources"